#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <iostream>
#include "test.tab.h"
#include "functions.h"

//extern int yyparse();     // Function generated by Bison
//extern FILE *yyin;        // Input file pointer for Bison
//extern int parse_string(const char* in); // Declare the function from parse.y

extern std::vector<Command> pipe_cmds;



int main(void) {
    char *input = NULL;


    while (1) {

        printf("$ ");
        yyparse();

// Execute commands based on 'input' here
// Remember to fork a new process and use execve

    }


    free(input);
    return (0);
}