#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <iostream>
#include "test.tab.h"

//extern int yyparse();     // Function generated by Bison
//extern FILE *yyin;        // Input file pointer for Bison
//extern int parse_string(const char* in); // Declare the function from parse.y

int main(void) {
    std::cout << "leggo" << std::endl;
    char *input = NULL;


    while (1) {
        printf("$ ");
        return yyparse();
// Execute commands based on 'input' here
// Remember to fork a new process and use execve

    }


    free(input);
    return (0);
}